### ISSUE TITLE
Survival - Problema de diseño - Ver a través de determinadas paredes

### ISSUE THREAD

**Issue by HaniwaMaster14** [Nachin1998/From-the-Woods#2]
Dentro del modo de juego Survival, ocurre que al acercarse a rocas determinados objetos del escenario (no ocurre en todos), se logra ver a través de ellos, facilitando la visualización de los enemigos a través. Esto ocurre cuando uno se pega a algunas rocas. No se puede disparar a través, atravesarlas, ni tampoco te generan daño los enemigos por las mismas, solo te ven y el jugador también a ellos.
**Pasos de reproducción:**
**1-** Iniciar modo Survival.
**2-** Desde el punto de Spawn desplazarse hacia adelante.
**3-** Hasta llegar a tener contacto con la roca principal (de nombre Roca_3_low (17)), la más grande del mapa (Que se encuentra en el medio del mismo).
**Resultado:** Esto lo que hará es permitir al jugador vea a través de la piedra y de esta manera tener la posibilidad de tomar ventaja sobre los enemigos. Como también minimizar la inmersión en la experiencia del juego.
Esto se puede reproducir en todos los casos de prueba en algunas piedras específicas del mapa.
**Ocurre en los siguientes elementos:** Roca_3_low (17), Roca_3_low (8), Roca_3_low (7), Roca_1_low, Roca_3_low (12)
Priority -> Minor
Esto se puede corregir quitándoles la transparencia a esos elementos del mapa
Se adjuntan enlaces de imagen y video de ejemplos de algunos de esos elementos con el problema indicado para mayor ilustración:
Imagen ilustrativa:
https://drive.google.com/file/d/1TvzWoYNxRtEm7ePzaSuRNnWqJZotMoIQ/view?usp=sharing
Caso 1: -> Roca_3_low (17)
https://drive.google.com/file/d/1GglaJAI4TfiYDqiV8Kogl04keLBxViug/view?usp=sharing
Caso 2: -> Roca_3_low (8)
https://drive.google.com/file/d/1emwwcOlP4ET28Zpv8YF1TcgYCYVXxtc_/view?usp=sharing

m_EditorVersion: 2019.4.8f1
m_EditorVersionWithRevision: 2019.4.8f1 (60781d942082)

**Comment by demianmiranda** [comment]
Puede que haya alguna piedra mas o dos, en las que pase esto. Avisanos si necesitas que generemos issues para las que queden por reportar con este tema @Nachin1998

**Comment by demianmiranda** [comment]
Solucionado en versión 0.7
