### ISSUE TITLE
Survival – Menú de pausa – Botones On y Off reanudan partida

### ISSUE THREAD

**Issue by HaniwaMaster14** [Nachin1998/From-the-Woods#3]
Lo que ocurre en este caso es que al pausar el juego y querer anular o encender el sonido del juego en el menú mencionado, cierran automáticamente la pausa sin aplicar ningún cambio y el juego continúa como si no se hubiera oprimido alguno de esos dos botones.
**Pasos de Reproducción:**
**1-** Ingresar a uno de los modos del juego
**2-** Oprimir el botón ‘Esc’ para detener el juego
**3-** Seleccionar botones del campo ‘Sound’, ON u OFF
**Resultado:** Al seguir estos pasos se verá como la pausa se cierra sin haber tenido que seleccionar botón ‘Resume’, para volver a la partida.
Esto ocurre siempre que se pausa el juego y se quiere usar esos botones
**Resultado esperado:** Que el juego al pausar el mismo, y presionar sobre una de las opciones de selección de sonido, On u Off, quite o active el mismo, para luego tener que oprimir el botón ‘Resume’ cuando el jugador se encuentre preparado para hacerlo.

Se adjunta enlace de video para mayor ilustración:
https://drive.google.com/file/d/1932W2N_8OlD0oKhn5TyMEAZw5McbUBaG/view?usp=sharing

m_EditorVersion: 2019.4.8f1
m_EditorVersionWithRevision: 2019.4.8f1 (60781d942082)

**Comment by demianmiranda** [comment]
Solucionado en versión 0.7
